import { PREFIX } from './constants';

export const FETCH = `${PREFIX}/FETCH`;
export const SET_INDEX = `${PREFIX}/SET_INDEX`;
export const FETCH_TOP_STORIES = `${PREFIX}/FETCH_TOP_STORIES`;
export const FETCH_SUCCESS = `${PREFIX}/FETCH_SUCCESS`;
export const FETCH_FAILED = `${PREFIX}/FETCH_FAILED`;
export const FETCH_TOP_STORIES_SUCCESS = `${PREFIX}/FETCH_TOP_STORIES_SUCCESS`;
export const FETCH_TOP_STORIES_FAILED = `${PREFIX}/FETCH_TOP_STORIES_FAILED`;
